// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn6OU6CNSn6xYigHi9rnDML8XhqEZOieA',
    appId: '1:790133033564:web:997a82cecd637b4ce03499',
    messagingSenderId: '790133033564',
    projectId: 'my-mozz-test-chat-app',
    authDomain: 'my-mozz-test-chat-app.firebaseapp.com',
    storageBucket: 'my-mozz-test-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvumT4r1pyMRRx6JK-JEDKTNX8KQajf40',
    appId: '1:790133033564:android:fd33c7805672cca5e03499',
    messagingSenderId: '790133033564',
    projectId: 'my-mozz-test-chat-app',
    storageBucket: 'my-mozz-test-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeaY7ksZ0BBjK69T-m4VkmaS7jmjKOO6g',
    appId: '1:790133033564:ios:cdc7f07413f4d08ee03499',
    messagingSenderId: '790133033564',
    projectId: 'my-mozz-test-chat-app',
    storageBucket: 'my-mozz-test-chat-app.appspot.com',
    iosBundleId: 'com.example.mozzTestTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeaY7ksZ0BBjK69T-m4VkmaS7jmjKOO6g',
    appId: '1:790133033564:ios:cdc7f07413f4d08ee03499',
    messagingSenderId: '790133033564',
    projectId: 'my-mozz-test-chat-app',
    storageBucket: 'my-mozz-test-chat-app.appspot.com',
    iosBundleId: 'com.example.mozzTestTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn6OU6CNSn6xYigHi9rnDML8XhqEZOieA',
    appId: '1:790133033564:web:019d00aa3ffacad6e03499',
    messagingSenderId: '790133033564',
    projectId: 'my-mozz-test-chat-app',
    authDomain: 'my-mozz-test-chat-app.firebaseapp.com',
    storageBucket: 'my-mozz-test-chat-app.appspot.com',
  );
}
